### ISSUE TITLE
In-Memory cache fills up indefinitely by default

### ISSUE THREAD

**Issue by halcy** [meraki-analytics/cassiopeia#40]
Right now, the in-memory cache only ever gets fuller. When pulling a lot of data from the API, this can start to be a problem. I'd propose either explicitly mentioning this and how to reset the cache in documentation, or (ideally) having a maximum size for the cache / maximum number of stored objects, with some expulsion policy (LRU?), and a sane default value to start off with (but this might be hard to do properly).

**Comment by robrua** [comment]
Hey - been planning on updating the caching stuff eventually to have configurable expiration periods for each type + some eviction policy. Haven't gotten around to it yet. For now you can just set the datastore to a new instance of Cache to clear it.

**Comment by jjmaldonis** [comment]
After almost two years we finally get to close this issue. This was fixed / added over a series of recent commits.

Some details:

The data sinks now support expiration timeouts! I.e. you can specify how long you want data to "live" in the cache or diskstore. If a piece of data is accessed that has expired, it will be removed from the data sink and the data will be refreshed. Currently, data will not be removed from the data sink until it is accessed, and it's up to you as the user to remove "old" data if it's taking up too much space / memory. You can do this via one of the following two methods:  The settings (available via `cass.configuration.settings`) now has 1) `.clear_sinks` and 2) `.expire_sinks` which 1) remove things from all data sinks and 2) remove all expired data from all data sinks. You can specify how long you want data to live in a datasink in your settings.

**Comment by martinzlocha** [comment]
Hi I have encountered the same issue but even after doing `.clear_sinks` and `.expire_sinks` the  issue persists. After maybe 5 minutes the memory usage grows from 70-120MB.

Here is some code which I am using to reproduce the issue:

```

I have the newest version from pip.

**Comment by jjmaldonis** [comment]
Thanks for the detailed bug report. We'll get a new release out asap to fix this.
