### ISSUE TITLE
'Siege' is not a valid StatSummaryType

### ISSUE THREAD

**Issue by riverphoenix** [meraki-analytics/cassiopeia#75]
Hi,

It seems that riotapi.get_stats throws an exception because of an update on the playerStatSummaryType (https://developer.riotgames.com/docs/game-constants) that now includes the new type 'Siege' for Nexus Siege games.

See below error:
```
C:\Django\cgames\common\util\lol_utils.py in get_lol_stats(summoner, c_user)
     45 
     46         try:
---> 47                 stats = riotapi.get_stats(summoner)
     48         except APIError as error:
     49                 return -1

C:\Envs\cgames\lib\site-packages\cassiopeia\core\statsapi.py in get_stats(summoner, season)
     36 
     37     stats = cassiopeia.dto.statsapi.get_stats(summoner.id, season.value if season else None)
---> 38     return {cassiopeia.type.core.common.StatSummaryType(summary.playerStatSummaryType): cassiopeia.type.core.stats.StatsSummary(summary) for summary in stats.playerStatSummaries}

C:\Envs\cgames\lib\site-packages\cassiopeia\core\statsapi.py in <dictcomp>(.0)
     36 
     37     stats = cassiopeia.dto.statsapi.get_stats(summoner.id, season.value if season else None)
---> 38     return {cassiopeia.type.core.common.StatSummaryType(summary.playerStatSummaryType): cassiopeia.type.core.stats.StatsSummary(summary) for summary in stats.playerStatSummaries}

c:\anaconda3\Lib\enum.py in __call__(cls, value, names, module, qualname, type, start)
    239         """
    240         if names is None:  # simple value lookup
--> 241             return cls.__new__(cls, value)
    242         # otherwise, functional API: we're creating a new Enum type
    243         return cls._create_(value, names, module=module, qualname=qualname, type=type, start=start)

c:\anaconda3\Lib\enum.py in __new__(cls, value)
    474                 if member._value_ == value:
    475                     return member
--> 476         raise ValueError("%r is not a valid %s" % (value, cls.__name__))
    477 
    478     def __repr__(self):

ValueError: 'Siege' is not a valid StatSummaryType
```

**Comment by jjmaldonis** [comment]
Thanks for the report. I believe I have fixed the bug now.Could you please re-pull and make sure the bug is fixed? If it is, you are welcome to close the issue. Thanks!

**Comment by riverphoenix** [comment]
In 'type\core\common.py' at line 331 you forgot the final comma and it gets an error. Once added everything works correctly.

Thanks for the quick fix!

**Comment by jjmaldonis** [comment]
Thanks for your help too.
