### ISSUE TITLE
'Assassinate' is not a valid StatSummaryType

### ISSUE THREAD

**Issue by riverphoenix** [meraki-analytics/cassiopeia#96]
The new assasinate type is not included in the StatsSummaryType and throws an exception

**Comment by jjmaldonis** [comment]
Thanks for the report. Is the game mode listed on [this](https://developer.riotgames.com/docs/game-constants) page? I can't seem to find it.  If not, could you please provide the exact name of the game mode (including capitalization) so we can add it properly?

**Comment by jjmaldonis** [comment]
Everspace (NA) on the discord found this out for me:

`"matchMode": "ASSASSINATE"`

I'll update it in the coming few days.

**Comment by zlehmann** [comment]
Hi jjmaldonis, any update on the assassinate update? I'm still getting exceptions.

**Comment by jjmaldonis** [comment]
@zlehmann @riverphoenix this should be fixed now. The problem is that this data is not updated in the API documentation, so I don't know which types need to be updated. I added `Assassinate` to the `StatSummaryType` and `ASSASSINATE` to the `GameMode`. There may be other places where the assassinate game type is used, and if you find any, please let me know 1) which enum to update and 2) exactly what string you are getting from the API.

If you still run into errors, providing me with an example to reproduce the error would be extremely helpful.

**Comment by zlehmann** [comment]
Hey Jason,

I'm still getting the errors after update:

return {cassiopeia.type.core.common.StatSummaryType(summary.playerStatSummaryType):
cassiopeia.type.core.stats.StatsSummary(summary) for summary in
stats.playerStatSummaries}

**Comment by jjmaldonis** [comment]
As I mentioned, an example would have been extremely helpful. You didn't even copy-paste the entire error message. At this point, I recommend you fix the problem yourself, then coming back with a full description of the problem and the solution so I can actually fix it rather than be forced to guess what's going on with almost no information. If you are having problems fixing the error, I recommend posting on the forums or asking in the discord channel.

**Comment by zlehmann** [comment]
Sorry, very new to this, I thought that was the part that would have been
helpful.

**Comment by jjmaldonis** [comment]
Ok sorry, I didn't realize that. But yeah if you can at least post the full error (even if it's long) and the code that you are using to produce the issue, then I actually have something to work with and can dig in to figure out what's going on. Unfortunately I have no clue what the problem is right now.

Also, if you are using `pip` to update Cass, make user you use this method: http://stackoverflow.com/questions/15268953/how-to-install-python-package-from-github

rather than `pip upgrade cassiopeia` which won't download the fix, because I didn't make a new release version for this fix.

Let me know if you're having issues.

**Comment by zlehmann** [comment]
Ahhhh, thank you so much! Using the method for updating that you linked did
the trick.
